nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api
        host_patterns:
            - ^api\.
    documentation:
        info:
            title: Train routing & analytics API
            description: API pour router un train d'une station A à B sur un réseau, calculer la distance parcourue et fournir des statistiques agrégées par code analytique.
            version: 1.0.0
        servers:
            - url: /api/v1
              description: Version 1 de l'API
        security:
            - bearerAuth: []



